[phases.setup]
nixPkgs = ["...", "openssl", "nodejs_20"]

[phases.install]
cmds = ["npm ci --legacy-peer-deps || npm install --legacy-peer-deps"]

[phases.build]
cmds = ["npx prisma generate", "npm run build"]

[phases.start]
cmd = "node .next/standalone/server.js"

[variables]
NODE_ENV = "production"
HOSTNAME = "0.0.0.0"
PORT = "3000"
DATABASE_URL = "file:/app/data/custom.db"
